### ISSUE TITLE
Column not found: 1054 Unknown column 'username' in 'field list'

### ISSUE THREAD

**Issue by Zhythero** [ryanarcel/ryanarcel-PokemonAPI-VueJS-Laravel#1]
Hi.

After migration and trying to register, I get this error in the registration form:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (SQL: insert into `users` (`username`, `email`, `password`, `updated_at`, `created_at`) values (kira, kira@mailinator.com, $2y$10$SLXh6.KkkyuskXh3pGT5aOmqRebo76IJ.mY5sxPoN990HWRBakrvq, 2022-04-06 02:19:16, 2022-04-06 02:19:16))
```

Please use migrations instead of an import of .sql file. Thank you.

**Comment by ryanarcel** [comment]
Hi, good morning.

I'm sorry but I did not use laravel migration in doing this project. I
preferred setting up my database directly in the phpmyadmin. I attached the
.sql file in the SQL folder located in the repository. Please import it in.
The database name is laravel-vue.
I just checked the file just now and I confirmed that I have the right
column name: 'username'. Thanks! Have a nice day.
[image: image.png]

**Comment by ryanarcel** [comment]
Hi, yes sir. I will add the migration files for tables.
